### ISSUE TITLE
Mumak improvements

### ISSUE THREAD

**Issue by pulkit24** [pulkit24/ToME#134]
Matt: -Some Mumak upgrades don't have any effect I don't think. Mumak archers aren't as fun as the melee ones used to be, and look less intimidating, something to consider.  I feel like the Mumak should be a devastating unit, not a mobile keep. Something like the original persian UU, but morre expensive and harder to bring down.

**Comment by pulkit24** [comment]
Language written for melee mumak.

**Comment by pulkit24** [comment]
See http://aok.heavengames.com/blacksmith/showfile.php?fileid=11446

**Comment by pulkit24** [comment]
Also Charging mode: http://aok.heavengames.com/cgi-bin/forums/display.cgi?action=ct&f=9,44230,,10

**Comment by Vardamir117** [comment]
The weapons swap works with task swap ID (villager mode in older AGE versions). In order for it to work, the melee and ranged mumak must be changed to the same class, given the same task swap ID, and have their ability to attack removed. They also must be given the ability to hunt (with odd parameters: you may have to copy the ability from the task-swapping elephant) set for every class or unit that it can interact with, to one or both variants.

When ordered to attack a class that only has a hunt ability set for the ranged version, a melee mumak will switch to the ranged version. This switch only occurs when ordered by the player, not for autoattacks. If the ability to hunt a class is given to both versions, the mumak would stay on the active version when ordered to attack said class.

An implementation for maximum flexibility would be to give both mumaks the ability to attack most classes, with exceptions like only the ranged version for ships and only the melee version for buildings. When fighting most units, the mumakil would not change modes, but it could be changed to melee by ordering an attack on an enemy building, even if that building was in the fog of war at the moment. Some other class that is almost available could be used for the swap to ranged.

**Comment by pulkit24** [comment]
Thanks for the explanation Vardamir! I was thinking for a sharp dichotomy by using the ranged mumak for all ranged classes, and melee for all melee. Perhaps they can share the siege and terror classes though. Another option is to use the packing/unpacking ability to manually switch modes, but that would mean no auto-attack.

**Comment by Vardamir117** [comment]
Wizards could be an interesting place to experiment with attack swapping techniques

**Comment by Vardamir117** [comment]
You should check this patch out: http://aok.heavengames.com/blacksmith/showfile.php?fileid=12733

Among other things, it allows a much better toggle solution (NewSkill Transform) that adds a new button that can toggle between two units with little restriction.

It also adds a lot of other features, including new trigger effects (teleport, Garrison source units into destination unit, more colors for display instructions, transform units to another type, rotate units...), units that attack and heal, units that can attack and build, can give the unload ability to other units, can make other IDs act like petards, can make other units self-heal...

It's a pretty amazing set of tools

**Comment by pulkit24** [comment]
Thanks Vardamir. I'll put it up on the thread for vote & debate.

Pack/unpack didn't work due to missing auto attack.
Task swap ID implemented using Attack type abilities instead of Hunt: melee mode for melee units & buildings, ranged mode for ranged units & ships. Mode changes on manual target. Auto attack continues with the existing mode. Starting mode is melee.
