### ISSUE TITLE
RMS Ideas

### ISSUE THREAD

**Issue by pulkit24** [pulkit24/ToME#196]
- [ ] - Numenor/ New Havens - everyone starts on single land zone with equal access to water. Water on one side, with large chunks of land beyond as havens for taking. Promotes naval expansion.
- [ ] - Eriador - hilly terrain. Elevation levels with 2-3 tile gaps making hills bigger and graduated. Top elevation has green mountains. Everyone starts in lowest elevation "valleys" with 1-2 lakes here and there (#valleys = #players + 1-2 lakes).
- [ ] - Misty Mountains - as before. Seasonal: green pines with green mountains, autumn with leafy terrains and mallorn stragglers, and snowy with snow mountains. Full of rocks, cliffs, mountains, pine patches and mix of rough terrains. Deer, boars and lots of wolves. Might be easy to wall off gaps in terrain. Ponds are eye candy only.
- [ ] - Mirkwood - as before. See Mirkwood in Blacksmith. Hill in the centre up for grabs? Roads connecting allied players?
- [ ] - Lorien - players start in isolation surrounded by a circle of mallorn trees 2-3 tree thick. Beyond this, players are separated by rivers with ample shallows.
- [ ] - Mordor - as before.
- [ ] - Moria - gold rush. Black forest but with cliffs instead of trees. Players start on the edge with trees at the edge, limited other resources. All gold and stone are at the center (in separate pockets) but guarded by goblins.
- [ ] - Breeland - as before. Farmsteads (village houses, Took houses, farmhouses, farms, horses, oxen in pens) sprinkled throughout for the taking. Marshes here and there - lakes of shallows - with shore fish. Roads connecting players.
- [ ] - Sea of Rhun - as before, but with no frills like mountains. Simple mediterranean with large central water, standard resources throughout and oxen. Perhaps small islands scattered throughout with troves, gold, and oxen.
- [ ] - Dead Marshes - see Tropicalago in Blacksmith
- [ ] - Forochel - no berries, no animals except Snow Wolves and White Wolves. Instead, every player gets small pond filled with fishes. Water on one side with a round bay coming in the centre, accessible by all players. Bay full of fishes. Map low on wood.
- [ ] - Arnor/Northern Kingdoms - arena map. May be with +1 random building and unit or hero. Large walled player spaces nearly touching each other, covering the whole map. No towers next to walls. Build within your walls or expand into next door opponents. No need for exploration.
- [ ] - Osgiliath/Anduin - single, thick river across the map vertically, with a medium central island. Ruins, stone and gold on island. Shallows connect both lands on either side to the island, thereby connecting to each other. Flags for all players on the island?
- [ ] - Angmar - snow mountains. Players start with a tower. Goblin camps scattered throughout the map that can only be taken by force. Comprise goblins, a house and a military building. Wolves as well.
- [ ] - Dale - ruins all around. Base terrains are roads of different types (can one construct on roads?). Water canals connecting players. Neat manicured square gardens are the only source of wood (shrubs?).
- [ ] - Sunlands - arabia-like Harad map. Sparse resources. Wild Mumak for boars.
- [ ] - Dagorlad - all players start without TC, with standard villagers, a scout, an archer, a swordsman and a banner-bearer. Also a hero? See M@Ancient Ruins in Blacksmith.
- [ ] - Gondor - small cities as starting base. Fortified with walls, towers, and castle. Only room for a few farms next to TC. Must build further buildings outside of base. Green and yellow land of rivers and stone cities. Plenty of resources.
- [ ] - Rohan - flat grassy plains. Wargs instead of wolves. Horses and sheep. Start with picket walls (incomplete), 2-3 houses, a mill and a stable.

**Comment by pulkit24** [comment]
Arabia - Arid desert with strategic elevations and cliffs, but sparse vegetation and water.
	Harad - Beware the wild mûmakil calves in these arid deserts: you can hunt them but so can they!
	Sunlands/Sutherland/Haradwaith - arabia-like Harad map. Sparse resources. Wild Mumak for boars.

Arena - The walls around your forest clearing are your only protection from the carnage in the middle.
	Fields of Cormallen - Set up camp and wage battles in these large open glades in the forest of Ithilien.
	Arnor/Northern Kingdoms - arena map. May be with +1 random building and unit or hero. Large walled player spaces nearly touching each other, covering the whole map. No towers next to walls. Build within your walls or expand into next door opponents. No need for exploration.

Archipelago - A group of large islands. You might not be the only inhabitant on yours.
	Isles - A group of large islands. You might not be the only inhabitant on yours.
	Tharbad - fertile land but sparse in trees (mostly shrubs). River flows through the middle, with shallows and one big road bridge. Roads connect players. Start with market, trade cart and tribute collector. See Danube in Blacksmith.

Baltic - An ocean with peninsulas and sheltered bays.
	Lake Evendim - A deep lake by the alpine mountains in Eriador, once a site of the capital city of Arnor.
	Angmar - snow mountains. Players start with a tower. Goblin camps scattered throughout the map that can only be taken by force. Comprise goblins, a house and a military building. Wolves as well.

Black Forest - Islands of grass in a sea of trees. Follow the paths through the forest to find your allies and enemies.
	Ithilien - Lush forested gardens of the Dúnedain, now abandoned, offer strategic elevations and ambush points.
	Mirkwood - as before. See Mirkwood in Blacksmith. Hill in the centre up for grabs? Roads connecting allied players?

Coastal - Where the land meets the ocean, with plenty of water and a large landmass for battles by land or by sea.
	Forlindon - The western-most coasts of Middle-earth, the Great Sea on one side and the Blue Mountains on the other.
	Breeland - as before. Farmsteads (village houses, Took houses, farmhouses, farms, horses, oxen in pens) + Mills sprinkled throughout for the taking. Capture Mills for tribute collection. Marshes here and there - lakes of shallows - with shore fish. Roads connecting players.

Continental - A large body of land surrounded by the sea; rivers may separate players and teams.
	Númenor - Relive the Akallabêth on this large island surrounded by the sea on all sides.
	Blue Mountains - simple coastal map. Adequate resources, few predators. 1-2 tight clumps of blue mountains and snow pines, with 1 capturable dwarf unit in each, and/or a dwarven tower.

Crater Lake - An island brimming with gold in the center of a caldera lake. Steep elevation and lack of trees make it hard to build there.
	The Shire - Play in the serene hills of the hobbit homeland.
	Osgiliath/Anduin - single, thick river across the map vertically, with a medium central island. Ruins, stone and gold on island. Shallows connect both lands on either side to the island, thereby connecting to each other. Flags for all players on the island?

Fortress - A walled city with gates and all the buildings you need to build up your forces quickly.
	Breeland - Towns with all the buildings you need to prosper quickly. Farmsteads abound in the region for you to capture.
	Gondor - small cities as starting base. Fortified with walls, towers, and castle. Only room for a few farms next to TC. Must build further buildings outside of base. Green and yellow land of rivers and stone cities. Plenty of resources. Scattered capturable beacons for scouting.

Ghost Lake - The central lake is frozen over, creating a no-man's land.
	Mordor -  Play on the ash plains of Gorgoroth or at the Sea of Nurnen. Vegetation is scare, trees burnt, and iron boars roam the black woods.
	Mordor - as before.

Gold Rush - A whole heap of gold and a few wolves in the middle of a desert.
	Enedwaith - A green land laid waste by rampant deforestation by Númenoreans of old, though rich in precious mines.
	Moria - gold rush. Black forest but with cliffs instead of trees. Players start on the edge with trees at the edge, limited other resources. All gold and stone are at the center (in separate pockets) but guarded by goblins.

Highland - Far from the ocean and heavily forested but with plenty of rivers and open space for maneuvers.
	Rohan - Horses graze freely in these open grasslands devoid of wolves or boars. Excellent for early expansion, though wargs roam on the fringes.
	Rohan - flat grassy plains. Wargs instead of wolves. Horses and sheep. Start with picket walls (incomplete), 2-3 houses, a mill and a stable.

Islands - Each player starts alone on an island; uninhabited islands may be rich with resources so be prepared to rule the sea.
	Tolfalas - Isolated islands at the mouths of Anduin; uninhabited islands may be rich with resources so be prepared to rule the sea.
	Numenor/ New Havens - everyone starts on single land zone with equal access to water. Water on one side, with large chunks of land beyond as havens for taking. Promotes naval expansion.

Mediterranean - An inland sea surrounded by land; sounds deceptively peaceful.
	Sea of Rhûn - A large inland sea, bordered by well-forested lands, home to the famed Kine of Araw.
	Sea of Rhun - as before, but with no frills like mountains. Simple mediterranean with large central water, standard resources throughout and oxen. Perhaps small islands scattered throughout with troves, gold, and oxen.

Migration - A tiny island that can't support you for long before you must move to the mainland, where the fighting is fierce.
	Team Islands - One island shared by you and your allies, and another inhabited by your enemies. The islands are not connected by shallows, so beware of enemy Transport Ships.
	Beleriand - a sinking land, scarcely any resources left. Rubble and ruins everywhere suggesting a formerly glorius settlement. Similar to Dead Marshes but with larger lands and no shallows.

Mongolia - Cliffs abound on these parched and endless steppes.
	Misty Mountains - Middle-earth's largest mountain range is beautiful to behold in the summers.
	Misty Mountains - as before. Seasonal: green pines with green mountains, autumn with leafy terrains and mallorn stragglers, and snowy with snow mountains. Full of rocks, cliffs, mountains, pine patches and mix of rough terrains. Deer, boars and lots of wolves. Might be easy to wall off gaps in terrain. Ponds are eye candy only.

Nomad - Your villagers begin scattered without a Town Center or Scout Cavalry. Will you build a town immediately or struggle to find the perfect location to settle?
	The Awakening - In the Years of the Trees the first people awoke at Cuiviénen, on the edge of the ancient Sea of Helcar.
	Dagorlad - all players start without TC, with standard villagers, a scout, an archer, a swordsman and a banner-bearer. Also a hero? See M@Ancient Ruins in Blacksmith.

Oasis - Nearly all of the wood is in the center of the map, so prepare to be chased around and around.
	Long Lake - Capturing the floating land in the middle of the lake will make or break your hold on the Long Lake.
	Lorien - players start in isolation surrounded by a circle of mallorn trees 2-3 tree thick. Beyond this, players are separated by rivers with ample shallows.

Rivers - Players are isolated by narrow rivers; numerous shallows must be guarded at all cost.
	Gondor - Life in the southern fiefs is peaceful, full of sheep, oxen and plenty of rivers.
	Dale - ruins all around. Base terrains are roads of different types (can one construct on roads?). Water canals connecting players. Neat manicured square gardens are the only source of wood (shrubs?).

Salt Marsh - Swampy lowlands full of shallows and rivers that can prohibit expansionistic building.
	Dead Marshes - A large expanse of eerie swamp full of shallows and stagnant water that can prohibit expansionistic building.
	Dead Marshes - see Tropicalago in Blacksmith

Scandinavia - In the northern wilderness the berry bushes have all frozen, but there are hungry animals to be hunted and plenty of gold to be found.
	Forochel - The bitterest of winters bites this bay of ice, where food is scarce and white wolves are hungry.
	Forochel - no berries, no animals except Snow Wolves and White Wolves. Instead, every player gets small pond filled with fishes. Water on one side with a round bay coming in the centre, accessible by all players. Bay full of fishes. Map low on wood.

Team Islands - One island shared by you and your allies, and another inhabited by your enemies. The islands are not connected by shallows, so beware of enemy Transport Ships.
	Mirkwood - City building will be a challenge in this dense labyrinth of dark forest infested by giant spiders.
	Mouths of Anduin - snaky lands reach into the vast waters of Anduin. Players start dangerously close to the beach making naval defences essential. Teams are divided by the river's fingers. Lots of fishes and fertile lands. Abundant in stone.

Yucatan - In the tropical rainforest food is abundant, but jaguars stalk beneath the canopy.
	Lórien - Time stands still in the Golden Wood as majestic mallorn trees withstand marauding goblins from orc dens outside.
	Eriador - hilly terrain. Elevation levels with 2-3 tile gaps making hills bigger and graduated. Top elevation has green mountains. Everyone starts in lowest elevation "valleys" with 1-2 lakes here and there (#valleys = #players + 1-2 lakes).

**Comment by Vardamir117** [comment]
Barrow downs - Verdant, open hill country home to many ruins. Despite the peaceful appearance, dangerous shades inhabit the downs

**Comment by pulkit24** [comment]
Trollshaws instead of Dead Marshes. 
Weathertop combined with Eriador.

**Comment by pulkit24** [comment]
Constants updated. Standard land & water resources updated.

**Comment by pulkit24** [comment]
All RMS completed.
