### ISSUE TITLE
Faulty technologies: Buttlery, Storehouses, Forest Wardens, Gardens of Lorien, Adamant Exploration, Mithril mining

### ISSUE THREAD

**Issue by xseryda** [pulkit24/ToME#212]
First of all, Buttlery has no effect right now.
Second - storehouses raising everything by 50% is way too big - Adamant Exploration has about the same price, only raises stone by 20%.

BUG - all the mentioned technologies do not work correctly -- now the PRODUCTION is increased (e.g. ridiculous *2 for Gardens of Lorien). To work correctly, the production has to be increased and the villager work rate decreased accordingly (some special magic for farms). 

To prove this I am enclosing a picture from the original game  - Mayans, which have all resources last 20% longer. This should be added to all of the mentioned technologies.

![snimek obrazovky 52](https://cloud.githubusercontent.com/assets/6108107/26750747/e8d763ea-4829-11e7-907e-37af677cd856.png)

I fixed the bug and several others in my local version based on the version released a month ago. But I also did some balance changes and I don't know if you would agree with them. Anyway I can send the files if you wish.

I can try to write all the bugs I discovered so far if you want. This one I found critical.

**Comment by pulkit24** [comment]
Please keep posting any bugs!

**Comment by xseryda** [comment]
I am creating an AI Jonas here https://github.com/xseryda/ToME using the 0.8 version. I also fix the bugs I am able to fix and try to comment all in the Changelog. At the end of the file you can see bugs I found and some of them I fixed. Note that I do also some minor balance changes, all of them mentioned in the Changelog. If you don't agree with them you of course don't have to use them.

**Comment by pulkit24** [comment]
Fixed
