### ISSUE TITLE
XML Ordering

### ISSUE THREAD

**Issue by Vardamir117** [pulkit24/ToME#215]
The XML is ordered incorrectly:

```
Data                    XML
Lorien                  Lorien
Lindon                 Lindon
ISENGARD           ARNOR
Gondor                Gondor
ARNOR                MORDOR
Mirkwood            Mirkwood
MORDOR            ANGMAR
Harad                  Harad
Rhovanion           Rhovanion
Minas Morgul      Minas Morgul
Umbar                 Umbar
Rohan                  Rohan
Eregion                Eregion
Rivendell              Rivendell
ANGMAR             ISENGARD
Dol Guldur          Dol Guldur
Rhun                   Rhun
Numenor            Numenor
```

**Comment by pulkit24** [comment]
Thanks! I’ve asked flagstone and AFFA to post their XML here too.

**Comment by AFFA-the-Cleric** [comment]
Hi All!

This is my XML

<?xml version="1.0" encoding="utf-8"?>
<configuration game="tome">
	<name>Tales of Middle-Earth</name>
	<path>ToME</path>
	<civilizations langId="10230" descId="20150" aiNameOffset="140" uiBaseId="51100" uiStride="20" uiOffset="2">
		<civilization id="0" name="gaia" soundFile="stream\random.mp3" scoutUnit="448" uniqueUnit="0" eliteUniqueUnit="0" uniqueUnitLine="0" uniqueUnitUpgrade="0" uniqueResearch="0" />
		<civilization id="2" name="lothlorien" soundFile="stream\Lothlorien.mp3" scoutUnit="448" uniqueUnit="8" eliteUniqueUnit="530" uniqueUnitLine="8" uniqueUnitUpgrade="360" uniqueResearch="3" />
		<civilization id="6" name="lindon" soundFile="stream\Lindon.mp3" scoutUnit="448" uniqueUnit="281" eliteUniqueUnit="531" uniqueUnitLine="281" uniqueUnitUpgrade="363" uniqueResearch="83" />
		<civilization id="7" name="arnor" soundFile="stream\Arnor.mp3" scoutUnit="448" uniqueUnit="41" eliteUniqueUnit="555" uniqueUnitLine="41" uniqueUnitUpgrade="365" uniqueResearch="16" />
		<civilization id="16" name="gondor" soundFile="stream\Gondor.mp3" scoutUnit="448" uniqueUnit="25" eliteUniqueUnit="554" uniqueUnitLine="25" uniqueUnitUpgrade="364" uniqueResearch="11" />
		<civilization id="9" name="mordor" soundFile="stream\Mordor.mp3" scoutUnit="751" uniqueUnit="291" eliteUniqueUnit="560" uniqueUnitLine="291" uniqueUnitUpgrade="366" uniqueResearch="59" />
		<civilization id="5" name="mirkwood" soundFile="stream\Mirkwood.mp3" scoutUnit="448" uniqueUnit="73" eliteUniqueUnit="559" uniqueUnitLine="73" uniqueUnitUpgrade="362" uniqueResearch="52" />
		<civilization id="3" name="angmar" soundFile="stream\Angmar.mp3" scoutUnit="751" uniqueUnit="40" eliteUniqueUnit="553" uniqueUnitLine="40" uniqueUnitUpgrade="361" uniqueResearch="61" />
		<civilization id="13" name="harad" soundFile="stream\Harad.mp3" scoutUnit="448" uniqueUnit="239" eliteUniqueUnit="558" uniqueUnitLine="239" uniqueUnitUpgrade="367" uniqueResearch="7" />
		<civilization id="14" name="rhovanion" soundFile="stream\Rhovanion.mp3" scoutUnit="448" uniqueUnit="282" eliteUniqueUnit="556" uniqueUnitLine="282" uniqueUnitUpgrade="368" uniqueResearch="9" />
		<civilization id="17" name="minasmorgul" soundFile="stream\Minas Morgul.mp3" scoutUnit="448" uniqueUnit="755" eliteUniqueUnit="757" uniqueUnitLine="755" uniqueUnitUpgrade="2" uniqueResearch="21" />
		<civilization id="18" name="umbar" soundFile="stream\Umbar.mp3" scoutUnit="448" uniqueUnit="692" eliteUniqueUnit="694" uniqueUnitLine="692" uniqueUnitUpgrade="398" uniqueResearch="49" />
		<civilization id="12" name="rohan" soundFile="stream\Rohan.mp3" scoutUnit="448" uniqueUnit="11" eliteUniqueUnit="561" uniqueUnitLine="11" uniqueUnitUpgrade="371" uniqueResearch="6" />
		<civilization id="4" name="eregion" soundFile="stream\Eregion.mp3" scoutUnit="448" uniqueUnit="232" eliteUniqueUnit="534" uniqueUnitLine="232" uniqueUnitUpgrade="370" uniqueResearch="5" />
		<civilization id="15" name="rivendell" soundFile="stream\Rivendell.mp3" scoutUnit="448" uniqueUnit="771" eliteUniqueUnit="773" uniqueUnitLine="771" uniqueUnitUpgrade="60" uniqueResearch="440" />
		<civilization id="1" name="isengard" soundFile="stream\Isengard.mp3" scoutUnit="448" uniqueUnit="725" eliteUniqueUnit="726" uniqueUnitLine="725" uniqueUnitUpgrade="432" uniqueResearch="24" />
		<civilization id="11" name="dolguldur" soundFile="stream\Dol Guldur.mp3" scoutUnit="751" uniqueUnit="763" eliteUniqueUnit="765" uniqueUnitLine="763" uniqueUnitUpgrade="27" uniqueResearch="4" />
		<civilization id="8" name="rhun" soundFile="stream\Rhun.mp3" scoutUnit="448" uniqueUnit="46" eliteUniqueUnit="557" uniqueUnitLine="46" uniqueUnitUpgrade="369" uniqueResearch="10" />
		<civilization id="10" name="numenor" soundFile="stream\Numenor.mp3" scoutUnit="448" uniqueUnit="827" eliteUniqueUnit="829" uniqueUnitLine="827" uniqueUnitUpgrade="450" uniqueResearch="445" />
	</civilizations>
</configuration>

**Comment by AFFA-the-Cleric** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration game="tome">
	<name>Tales of Middle-Earth</name>
	<path>ToME</path>
	<civilizations langId="10230" descId="20150" aiNameOffset="140" uiBaseId="51100" uiStride="20" uiOffset="2">
		<civilization id="0" name="gaia" soundFile="stream\random.mp3" scoutUnit="448" uniqueUnit="0" eliteUniqueUnit="0" uniqueUnitLine="0" uniqueUnitUpgrade="0" uniqueResearch="0" />
		<civilization id="2" name="lothlorien" soundFile="stream\Lothlorien.mp3" scoutUnit="448" uniqueUnit="8" eliteUniqueUnit="530" uniqueUnitLine="8" uniqueUnitUpgrade="360" uniqueResearch="3" />
		<civilization id="6" name="lindon" soundFile="stream\Lindon.mp3" scoutUnit="448" uniqueUnit="281" eliteUniqueUnit="531" uniqueUnitLine="281" uniqueUnitUpgrade="363" uniqueResearch="83" />
		<civilization id="7" name="arnor" soundFile="stream\Arnor.mp3" scoutUnit="448" uniqueUnit="41" eliteUniqueUnit="555" uniqueUnitLine="41" uniqueUnitUpgrade="365" uniqueResearch="16" />
		<civilization id="16" name="gondor" soundFile="stream\Gondor.mp3" scoutUnit="448" uniqueUnit="25" eliteUniqueUnit="554" uniqueUnitLine="25" uniqueUnitUpgrade="364" uniqueResearch="11" />
		<civilization id="9" name="mordor" soundFile="stream\Mordor.mp3" scoutUnit="751" uniqueUnit="291" eliteUniqueUnit="560" uniqueUnitLine="291" uniqueUnitUpgrade="366" uniqueResearch="59" />
		<civilization id="5" name="mirkwood" soundFile="stream\Mirkwood.mp3" scoutUnit="448" uniqueUnit="73" eliteUniqueUnit="559" uniqueUnitLine="73" uniqueUnitUpgrade="362" uniqueResearch="52" />
		<civilization id="3" name="angmar" soundFile="stream\Angmar.mp3" scoutUnit="751" uniqueUnit="40" eliteUniqueUnit="553" uniqueUnitLine="40" uniqueUnitUpgrade="361" uniqueResearch="61" />
		<civilization id="13" name="harad" soundFile="stream\Harad.mp3" scoutUnit="448" uniqueUnit="239" eliteUniqueUnit="558" uniqueUnitLine="239" uniqueUnitUpgrade="367" uniqueResearch="7" />
		<civilization id="14" name="rhovanion" soundFile="stream\Rhovanion.mp3" scoutUnit="448" uniqueUnit="282" eliteUniqueUnit="556" uniqueUnitLine="282" uniqueUnitUpgrade="368" uniqueResearch="9" />
		<civilization id="17" name="minasmorgul" soundFile="stream\Minas Morgul.mp3" scoutUnit="448" uniqueUnit="755" eliteUniqueUnit="757" uniqueUnitLine="755" uniqueUnitUpgrade="2" uniqueResearch="21" />
		<civilization id="18" name="umbar" soundFile="stream\Umbar.mp3" scoutUnit="448" uniqueUnit="692" eliteUniqueUnit="694" uniqueUnitLine="692" uniqueUnitUpgrade="398" uniqueResearch="49" />
		<civilization id="12" name="rohan" soundFile="stream\Rohan.mp3" scoutUnit="448" uniqueUnit="11" eliteUniqueUnit="561" uniqueUnitLine="11" uniqueUnitUpgrade="371" uniqueResearch="6" />
		<civilization id="4" name="eregion" soundFile="stream\Eregion.mp3" scoutUnit="448" uniqueUnit="232" eliteUniqueUnit="534" uniqueUnitLine="232" uniqueUnitUpgrade="370" uniqueResearch="5" />
		<civilization id="15" name="rivendell" soundFile="stream\Rivendell.mp3" scoutUnit="448" uniqueUnit="771" eliteUniqueUnit="773" uniqueUnitLine="771" uniqueUnitUpgrade="60" uniqueResearch="440" />
		<civilization id="1" name="isengard" soundFile="stream\Isengard.mp3" scoutUnit="448" uniqueUnit="725" eliteUniqueUnit="726" uniqueUnitLine="725" uniqueUnitUpgrade="432" uniqueResearch="24" />
		<civilization id="11" name="dolguldur" soundFile="stream\Dol Guldur.mp3" scoutUnit="751" uniqueUnit="763" eliteUniqueUnit="765" uniqueUnitLine="763" uniqueUnitUpgrade="27" uniqueResearch="4" />
		<civilization id="8" name="rhun" soundFile="stream\Rhun.mp3" scoutUnit="448" uniqueUnit="46" eliteUniqueUnit="557" uniqueUnitLine="46" uniqueUnitUpgrade="369" uniqueResearch="10" />
		<civilization id="10" name="numenor" soundFile="stream\Numenor.mp3" scoutUnit="448" uniqueUnit="827" eliteUniqueUnit="829" uniqueUnitLine="827" uniqueUnitUpgrade="450" uniqueResearch="445" />
	</civilizations>
</configuration>

**Comment by AFFA-the-Cleric** [comment]
Hi Pilkit, the GitHub messenger cannot allow me to post my xml file, it says file don't supported...also tried to copy and paste the content of my xml file, but it will simply don't shows up!

**Comment by AFFA-the-Cleric** [comment]
[tome.txt](https://github.com/pulkit24/ToME/files/1420249/tome.txt)

**Comment by Vardamir117** [comment]
Two other issues with the XML:

The referenced sound files don't exist. Sound/Stream is full of Aztecs.mp3 and so forth, not the names here.

Civ IDs should be in the order that civilizations appear in the history section. The sound of Civ ID 1 gets played when the first history entry is selected.

**Comment by AFFA-the-Cleric** [comment]
So, nothing we can edit manually our own XML file, maybe changing the civ ID?!

**Comment by flagstone** [comment]
Hi,
Here is my tome.xml.
Had to put it a zip, to make github accept it.
Flagstone.
[tome.zip](https://github.com/pulkit24/ToME/files/1422287/tome.zip)

**Comment by pulkit24** [comment]
XML ordering fixed. Thanks for all your help, everyone!
Please download the latest version and let me know if it fixes the issues for you.

Closing this issue now. If you still have the problem feel free to reopen.
