### ISSUE TITLE
Advancement issue

### ISSUE THREAD

**Issue by jlcarroll** [pulkit24/ToME#220]
Single Player, human player Arnor, with a Castle and House of Healing, the age advancement button remains greyed out until (for example) the Lore Vault is constructed.  (Forge and Siege Workshop was
used to advance previously, not a Castle [if that matters].)

If this can't be reproduced, I can upload a savegame at the point where the lore vault is not quite
constructed, if this would help track down the flaw.  (Or maybe it's not a flaw, in which case the
text for what is needed for age advancement should be amended.)

**Comment by pulkit24** [comment]
Thanks, will investigate. IIRC the Castle is now an optional building to advanced to the Third Age, not the Great Years, due to the fact that it is now available right from the Second Age. I'll double check.

**Comment by pulkit24** [comment]
Incorrect min tech required, fixed.
