### ISSUE TITLE
Lothlorien History Text named incorrectly

### ISSUE THREAD

**Issue by Vardamir117** [pulkit24/ToME#228]
The game expects Civ_Lothlorien, but the text file is called Civ_Lorien

**Comment by pulkit24** [comment]
Is this fixed? Why did you close this issue?

**Comment by Vardamir117** [comment]
I'd renamed the text file on Dropbox.

Since seeing them ingame, I've noticed a number of typos and formatting improvements, The whole set should probably be reacquired now.
