### ISSUE TITLE
doesnt run

### ISSUE THREAD

**Issue by Kupfermichl** [pulkit24/ToME#239]
when i launched the game .. it sais ( couldn't run specified executable)
how can i fix this.
I have installed the AOE ii Age of Kings and the Conqueres from the box set. I m running it on windows 10

**Comment by pulkit24** [comment]
Hi Kupfermichl,

What's the path to your AoK installation folder?

**Comment by Kupfermichl** [comment]
Thanks, meanwhile it is functioning
