### ISSUE TITLE
0.8.12 run error

### ISSUE THREAD

**Issue by SirMew** [pulkit24/ToME#241]
There's a tech tree error preventing me from starting a game or the editor.

_Invalid tech tree marker (expected NTT, version 1): ail, version 41_

**Comment by Barhir** [comment]
I get the same error, I've attatched a screenshot.
![image](https://user-images.githubusercontent.com/42354006/45315131-77077a00-b52b-11e8-9886-13beee4473a4.png)

**Comment by pulkit24** [comment]
Have you tried the latest 0.8.13?
