### ISSUE TITLE
Issues with certain technologies

### ISSUE THREAD

**Issue by MangyanMan** [pulkit24/ToME#243]
- [ ] Hillmen Alliance of Angmar makes war hall techs useless, should be removed once this tech has been researched, same with King's Men research for Numenor

- [ ] Necromancy tech for Dol Guldur is useless since they have no access to black orcs, since the tech does not affect normal orcs

- [ ] Mumak husbandry research does not affect mumak price and disables  Bloodlust tech

- [ ] Mordor and Numenor have no Cram tech?

- [ ] Ironmongery tech missing

- [ ] Rivendell hp bonus per upgrade on foot units not working

- [ ] Atani Nobleman upgrade is quite useless, should give more benefits to make it a good investment and to make Cardolan path more satisfying to choose

**Comment by JohnTheLate** [comment]
3, 4, 5 fixed, 6 and 7 fixed by Pulkit before, 1 & 2 need debate
