### ISSUE TITLE
0.8.11 tech tree error

### ISSUE THREAD

**Issue by Barhir** [pulkit24/ToME#244]
I'm running 0.8.11 since 0.8.12 has another tech tree error, it was working fine before but now it has this error:
![image](https://user-images.githubusercontent.com/42354006/45589821-a13eaa80-b924-11e8-8ca0-03035f5f3806.png)
Thanks

**Comment by Barhir** [comment]
I think it may be a problem with the vanilla installation. My laptop's DVD drive is broken so I copied the game files from my desktop onto my laptop. The game launches but when I start/create a game/scenario it crashes with the above error. It happens in 0.8.11 and 0.8.13 afaik, but I think this is only this computer's problem since ToME runs fine on my other PC.

**Comment by pulkit24** [comment]
Have you tried the latest 0.8.13?
