### ISSUE TITLE
Multiplayer gameplay

### ISSUE THREAD

**Issue by mehmetyasararas** [pulkit24/ToME#247]
Hello,

Great work. Congratulations for new patch. Iam waiting for version 1.0 patiently.
I have a question , ı cant play it multiplayer , I try it in Multiplayer menu many times (TCP/IP LAN LOCAL...) with my friend but it doesnt work. Can you help for this issue.

**Comment by JohnTheLate** [comment]
Alternatively, you have to forward your ports. See this post: http://aok.heavengames.com/cgi-bin/forums/display.cgi?action=ct&f=3,37714,,60
