### ISSUE TITLE
Opening other website/thread

### ISSUE THREAD

**Issue by Bigbossbro08** [pulkit24/ToME#248]
I think this mod should've other websites or thread like discord/reddit in order to have more discussion about the mod.
Roughly a feature request just saying in order to have more joint discussion and joining with more people that's it.
Edit: John The Late and 1415 from discord already opened unofficial discord server for now. I hope devs will see the server. link: https://discord.gg/jWBwzb4

**Comment by Barhir** [comment]
Yeah I'm for a discord server

**Comment by Bigbossbro08** [comment]
Unofficial for now ToME discord server. https://discord.gg/jWBwzb4
