### ISSUE TITLE
Tales of Middle-Earth and Advanced Genie Editor

### ISSUE THREAD

**Issue by Belcazzi** [pulkit24/ToME#249]
Hello, 

To begin with, the mod is fantastic, thanks a lot for your work ! Now I'll go straight to the point : I want to modify some things in the mod, and by "some things", i mean the quantity of ressources availables in trees, gold mines, animals, etc... and that's pretty much it ! But each time I make just one of those modifications, I end up, with the infamous "Invalid tech tree marker (expected NTT, version 1): ail, version 41" error each time I try to start a match (when the files are unmodified, the mod works perfectly).

I run the game on Windows XP service pack 3, my version of the mod is the 0.8.13. So in short, is it even possible to modify the ToME file with Advanced Genie Editor or is it a lost cause ? :P

Thanks in advance for your answer !

**Comment by Barhir** [comment]
Sorry I can't help much here, but I'm pretty sure you can edit it with AGE - I have done in previous versions of ToME and it worked fine.

**Comment by SirMew** [comment]
Yea i had this issue before when i attempted to modify the data files. It's an issue with Janworks tech tree, but i have a sneaky suspicion that you need to use specific versions of AGE. A while back TriRem believed you needed to uninstall the tech tree to successfully edit, however Jan claims this is not necessary.

**Comment by Belcazzi** [comment]
I tried with AGE 2017 and 2018 and ended up with the same result, what do you mean by "uninstalling the tech tree exactly" ?

**Comment by Belcazzi** [comment]
Or maybe i'm doing it wrong in the "Open Files..." Screen where you enter the location of the .dat, language.dll and the DRS files. At the moment it's like this :
Compressed Data : C:\program Files\Microsoft Game\Age of Empires II\Games\ToME\Data\empires2_x1_p1.dat

Language file location : C:\program Files\Microsoft Game\Age of Empires II\Games\ToME\Data\language.dll
Language x1 file location : C:\program Files\Microsoft Game\Age of Empires II\Games\ToME\Data\language_x1.dll
Language p1 file location : C:\program Files\Microsoft Game\Age of Empires II\Games\ToME\Data\language_p1.dll
Path for DRS files : C:\program Files\Microsoft Game\Age of Empires II\Data
Path for mod DRS files : C:\program Files\Microsoft Game\Age of Empires II\Games\ToME\Data
"Write language files" and "Write to the latest file instead of the base file" are unchecked and there's nothing in "Custom path override", "Extra 1st priority DRS file" and "Path for loose SLP files"

Could this be the source of my problem ?

**Comment by Belcazzi** [comment]
I tried with Age 2017 and 2018 and ended up with the same result, can I ask you which versions of AGE you are referring to ?

And Also What do you mean by "uninstalling the tech tree" exactly"


Or maybe i'm doing it wrong in the "Open Files..." Screen where you enter the location of the .dat, language.dll and the DRS files. At the moment it's like this :
Compressed Data : C:\program Files\Microsoft Game\Age of Empires II\Games\ToME\Data\empires2_x1_p1.dat

Language file location : C:\program Files\Microsoft Game\Age of Empires II\Games\ToME\Data\language.dll

Language x1 file location : C:\program Files\Microsoft Game\Age of Empires II\Games\ToME\Data\language_x1.dll

Language p1 file location : C:\program Files\Microsoft Game\Age of Empires II\Games\ToME\Data\language_p1.dll

Path for DRS files : C:\program Files\Microsoft Game\Age of Empires II\Data

Path for mod DRS files : C:\program Files\Microsoft Game\Age of Empires II\Games\ToME\Data

"Write language files" and "Write to the latest file instead of the base file" are unchecked and there's nothing in "Custom path override", "Extra 1st priority DRS file" and "Path for loose SLP files"

I tried different combinations of settings but it never worked

Could this be the source of my problem ? I know i'm being insistant, but I thought this topic might be useful for other peoples with the same problem ! :)

**Comment by JohnTheLate** [comment]
@Belcazzi you have to do the following things:
Download this: http://aok.heavengames.com/blacksmith/showfile.php?fileid=12694
1. Open ToME's data file in the new tech tree editor and export the tech tree. 
2. Do your changes in AGE.
3. Load your modified data file in the NTT editor again.
4. Import the changed tech tree and save the data file.

The problem lies in AGE not knowing when NTT data is present, and deleting it every time you save the data file with it.

**Comment by Belcazzi** [comment]
@JohnTheLate Thanks a lot, it worked ! You're officially my new hero ! For those who'd use the same method, when tou're finished with the manipulation : don't use the base launcher to play, use the one created by the NTT Editor in "C:\Program Files\Microsoft Games\Age of Empires II\age2_x1" (It IS supposed to do that right ?).

Anyway, thanks a bunch everyone !
